- .github/workflows/app-ci.yml
- README.md
- lefthook.yml
+ git hook 설치를 쉽게 도와주는 스크립트
+  [설치 가이드](https://github.com/Arkweid/lefthook/blob/master/docs/full_guide.md)
+ 설치 후 `lefthook install` 입력시 hook 설치를 하면 사용 가능
+ pull request 진행 시 analyze, format, build 실행
+ upload-artifact 에는 working-directory가 적용이 안되므로 다음에 할 때는 path를 전부 적어줘야 겠다.
> CI tool 추가 

- deep_learning/recycle_dataset/recycle_dataset.py
보안문제로 누구나 데이터 다운로드 받게 하는것을
데이터를 다운받고 로컬 경로로 데이터 설정하게 path로 바꿈.
> 데이터 다운로드 받는것 로컬 데이터로 수정

- .gitignore
gitignore.io 에서 git, python, vscode, flutter 에 대한 gitignore를 받아 만들었습니다.
> .gitignore 추가

- .gitignore
Fix #16 
+ app/**/lib 폴더가 ignore 되는 현상이 발생
+ .gitignore 의 사용하지 않는 파이썬 빌드 관련한 부분을 제거
> Fix #16 .gitignore에 안 쓰는 부분 삭제, app/**/lib 충돌 해결

- deep_learning/inobus_pet_v1_classification (1).ipynb
> inobus_pet_v1 노트북 구현

- deep_learning/inobus_pet_v1/inobus_pet_v1.py
학습할때 resize 하는것 보다 resize하고 데이터 올림.
(다운로드 빠름, Storage 비용)
> 이노버스 데이터 사이즈 변경

- app/inobus/android/app/build.gradle
- app/inobus/android/app/src/main/AndroidManifest.xml
- app/inobus/ios/Runner/AppDelegate.swift
- app/inobus/ios/Runner/Info.plist
- app/inobus/lib/frame/home.dart
- app/inobus/lib/main.dart
- app/inobus/lib/page/loading.dart
- app/inobus/lib/page/map.dart
- app/inobus/lib/page/menu.dart
- app/inobus/lib/page/qr.dart
- app/inobus/lib/page/rank.dart
- app/inobus/pubspec.lock
- app/inobus/pubspec.yaml
앱 주요 색상 변경(blue -> green)
하단 네비게이션 바 움직임 완성
> feat: Create App frame (issue #31)

- backend/routes/devices.py
> 구현: 모든 쓰샘 기기의 리스트 조회 #62

- backend/routes/devices.py
- backend/utils/distance.py
+ utils/distance.py에 두 좌표간의 거리 계산
+ routes/devices.py에서 "/nearby" API 구현
> 구현: 사용자 근처 쓰샘 리스트 반환 구현

- app/inobus/assets/test/organizations.json
- app/inobus/lib/main.dart
- app/inobus/lib/page/rank.dart
- Expanded : 남는 구간에 맞는 크기 지정
- ListView :  text를 스크롤로 보이게
issue #73
> 구현 : 4위 이하 랭크 스크롤로 여러개 보이게 만들기

- app/inobus/lib/frame/home.dart
- 하단 네비게이션 바 카메라 아이콘 QR 아이콘으로 변경
- 아이콘 아래 설명을 영어에서 한글로 변경
issue #74
> 추가 : 앱 상단 바에 회사 이미지 로고 추가

- deep_learning/README.md
- deep_learning/requirements.txt
새로운 venv에서 시도해봤는데 오류가 맞네요.
버전 수정했고, pip upgrade 하는것도 추가했습니다.
Closes #83
> 버그: deep_learning requirements.txt 버전 고침

- app/inobus/android/app/src/main/AndroidManifest.xml
- app/inobus/ios/Runner/Info.plist
- app/inobus/lib/page/login.dart
- app/inobus/lib/page/menu.dart
- app/inobus/lib/page/version.dart
- app/inobus/pubspec.lock
- app/inobus/pubspec.yaml
> 구현 : 메뉴 페이지 구성 틀 만들기

- deep_learning/inobus_pet_v3/__init__.py
- deep_learning/inobus_pet_v3/inobus_pet_v3.py
- deep_learning/inobus_pet_v3_classification.ipynb
- deep_learning/inobus_pet_v3_classification_imagenet.ipynb
예전에 실험했던 3번째 실험 (중간발표에서 발표한것) 올림.
> 구현: 이노버스 v3

- app/inobus/android/app/src/main/AndroidManifest.xml
- app/inobus/ios/Runner/AppDelegate.swift
- 구글지도 사용을 위한 api key 변경
- 이노버스 이메일로 google cloud platform 에서 key 발급 적용
Issue #102
> 수정 : 이노버스 공식으로 key 변경

- backend/models/data.py
- backend/models/device.py
- backend/models/organization.py
- backend/models/user.py
- backend/utils/datetime.py
- Nested model에 모든 정보를 저장할 필요 없이 id만 저장하도록 수정
- datetime 포맷 지정이 가능한 필드 생성하여 적용
- example에 id를 _id로 변경
- point 필드를 optional로 변경
> 버그: 중접모델 타입, 날짜 포맷 수정

- deep_learning/tools/augmentators/kernel.py
- deep_learning/tools/data_augmentation.py
예시:
위에서부터 gaussian blur, sharpen, box blur
> 구현: Filter를 이용한 augmentation 구현

- iot/install.sh
- iot/main.py
- iot/mqtt_client.service
- iot/mqtt_setting.py
- systemd에 시스템 시작 시 서버 실행하도록 등록
- iot 설치 스크립트 추가
- mqtt client initialized 상태 확인 속성 추가
> 추가: mqtt 배포 스크립트 및 initialize 속성 추가

- backend/routes/users.py
> 구현: 유저가 최근 6개월간 월별 포인트 실적 조회

- deep_learning/dataset/inobus_pet_v3_616/__init__.py
- deep_learning/dataset/inobus_pet_v3_616/inobus_pet_v3_616.py
> 구현: inobus_v3 데이터 616 사이즈.

- app/inobus/.gitignore
- app/inobus/ios/Runner/AppDelegate.swift
- fvm 파일 .fvm/flutter_sdk 추가
- apple swift 문제 해결
> 수정 : .fvm 파일 ignore

- app/inobus/lib/pages/support/support_page.dart
> 구현 : 오픈 url 연결

- app/inobus/lib/pages/barcode_page.dart
- app/inobus/lib/pages/introduction/1_login_page.dart
- app/inobus/lib/pages/introduction/2_after_login_page.dart
- app/inobus/lib/pages/map_page.dart
- app/inobus/lib/pages/market_page.dart
- app/inobus/lib/pages/pages.dart
- app/inobus/lib/pages/point_page.dart
- app/inobus/lib/routes.dart
- app/inobus/lib/widgets/app_drawer.dart
- 바코드에 박스 씌우기
- 에코마켓 추가
- 이달의 추첨상품은 회사 페이지로 이동
> 구현 : UI 수정

- app/inobus/lib/pages/barcode_page.dart
- app/inobus/lib/pages/information/use_lottery.dart
- app/inobus/lib/pages/user_history_page.dart
- 사용자 월별 포인트 값 반대로 인것 수정
- 글자 수정
- 버튼 크기 수정
> 수정 : 에러 수정
